Repository Elias-Manica/Linkr-back, pull requests merged in 2022-10, with the labels that each got.

#6 Feat: searchUsers
  src/controllers/helper.controllers.js
  src/controllers/users.controller.js
  src/repositories/users.repositories.js
  src/routers/users.router.js
Labels: enhancement

#7 Feat/login
  package-lock.json
  package.json
  src/controllers/auth.controllers.js
  src/controllers/helper.controllers.js
  src/middlewares/auth.middlewares.js
  src/repositories/auth.repositories.js
  src/routers/auth.routers.js
  src/schemas/auth.schemas.js
Labels: enhancement

#10 feat(searchUsers) fixing a bug where the server would crash after a bad request.
  src/controllers/users.controller.js
  src/repositories/users.repositories.js
Labels: bugfix

#11 Feat/logout and Login
  src/controllers/auth.controllers.js
  src/middlewares/auth.middlewares.js
  src/repositories/auth.repositories.js
  src/routers/auth.routers.js
Labels: enhancement

#12 changing to POST request to get the right data for the search function.
  src/controllers/users.controller.js
  src/routers/users.router.js
Labels: bugfix

#17 feat(goToUser) - changes on the query to send some infos on the user posts page
  package-lock.json
  src/controllers/users.controller.js
  src/repositories/users.repositories.js
  src/routers/users.router.js
Labels: refactor

#19 Feat/auth
  src/controllers/auth.controllers.js
Labels: enhancement

#20 feat: like and dislike a post.
  src/controllers/posts.controller.js
  src/repositories/posts.repositories.js
  src/routers/posts.router.js
Labels: enhancement

#22 Feat/comment post : the server now is able to receive and insert comments into db
  src/controllers/posts.controller.js
  src/middlewares/post.middleware.js
  src/repositories/posts.repositories.js
  src/routers/posts.router.js
Labels: enhancement

#27 Feat/repost
  src/controllers/posts.controller.js
  src/database/database.js
  src/middlewares/post.middleware.js
  src/repositories/posts.repositories.js
  src/routers/posts.router.js
Labels: enhancement, bugfix
